version: "3.2"

services:
  nacos:
    image: nacos/nacos-server
    environment:
      MODE: standalone
    ports:
      - "8848:8848"
      - "9848:9848"

  mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - "/home/hy/work/NewsRecommend/backend/mysql/data:/var/lib/mysql"
      - "/home/hy/work/NewsRecommend/backend/mysql/conf:/etc/mysql/conf.d/"
      # - "/home/hy/work/NewsRecommend/backend/mysql/init:/docker-entrypoint-initdb.d"

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - nacos

  news-service:
    build: ./news-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - nacos

  operation-service:
    build: ./operation-service
    ports:
      - "8085:8085"
    depends_on:
      - mysql
      - nacos
